

# This file was *autogenerated* from the file /home/rota1001/ctf/CryptoHackPractice/Challenges/EllipticCurve/tempCodeRunnerFile.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100)
for i in range(_sage_const_100 ):
#     data = {}
#     data["option"] = "sign_time"
#     r.sendlineafter(b"\n", str(data).replace("\'", "\""))
#     print(r.recvline())

